name: OpenVPN
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999
    steps:


    - name: Install openVPN
      run: |
        sudo su
        sudo apt update && apt install curl openvpn -y
        sudo curl -O https://raw.githubusercontent.com/galih-prasetyo/ngrok-openvpn/main/openvpn-install.sh
        sudo chmod +x openvpn-install.sh
        sudo ./openvpn-install.sh
      
    - name: Loop
      run: |
        while true; do
          sleep 60
        done
