name: Setup HTTPS Proxy Server

on: [push, pull_request]

jobs:
  proxy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      run: sudo apt-get update && sudo apt-get install -y docker.io

    - name: Run Squid Proxy in Docker
      run: |
        docker run -d --name squid-proxy \
        -p 3128:3128 \
        -e USERNAME=${{ secrets.PROXY_USERNAME }} \
        -e PASSWORD=${{ secrets.PROXY_PASSWORD }} \
        sameersbn/squid:latest

    - name: Test Proxy Server
      run: curl -x http://${{ secrets.PROXY_USERNAME }}:${{ secrets.PROXY_PASSWORD }}@localhost:3128 https://www.google.com
