name: Setup HTTPS Proxy Server

on: [push, pull_request]

jobs:
  proxy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Squid
      run: sudo apt-get update && sudo apt-get install -y squid apache2-utils

    - name: Configure Squid
      run: |
        sudo cp squid.conf /etc/squid/squid.conf
        sudo cp passwords /etc/squid/passwords
        sudo chmod o+r /etc/squid/passwords

    - name: Start Squid Service
      run: sudo systemctl restart squid

    - name: Test Proxy Server
      run: curl -x http://username:password@localhost:3128 https://www.google.com
