name: OpenVPN
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999
    steps:


    - name: Install openVPN
      run: |
        apt update
        apt upgrade
        apt install ca-certificates wget net-tools gnupg
        wget -qO - https://as-repository.openvpn.net/as-repo-public.gpg | apt-key add -
        echo "deb http://as-repository.openvpn.net/as/debian focal main">/etc/apt/sources.list.d/openvpn-as-repo.list
        apt update
        apt install openvpn-as
      
    - name: Loop
      run: |
        while true; do
          sleep 60
        done
